//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traveler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.TravelerInformations = new HashSet<TravelerInformation>();
        }
    
        public int ID { get; set; }
        public Nullable<int> TourID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<System.DateTime> BookingDay { get; set; }
        public string BookingCode { get; set; }
        public string Status { get; set; }
        public Nullable<int> SlotNumber { get; set; }
        public string Note { get; set; }
        public string ContactPhoneNumber { get; set; }
        public string ContactName { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Tour Tour { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TravelerInformation> TravelerInformations { get; set; }
    }
}
