//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traveler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int ID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> TourID { get; set; }
        public Nullable<int> StarNumber { get; set; }
        public string RatingContent { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Tour Tour { get; set; }
    }
}
