//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traveler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tour()
        {
            this.Books = new HashSet<Book>();
            this.Ratings = new HashSet<Rating>();
            this.Schedules = new HashSet<Schedule>();
        }
    
        public int ID { get; set; }
        public string TourName { get; set; }
        public Nullable<int> DestinationID { get; set; }
        public Nullable<int> SlotNumber { get; set; }
        public Nullable<System.DateTime> DepartureDay { get; set; }
        public Nullable<System.DateTime> EndDay { get; set; }
        public Nullable<int> DepartureLocationID { get; set; }
        public Nullable<double> Price { get; set; }
        public string Hotel { get; set; }
        public Nullable<int> ViewNumber { get; set; }
        public string GatherPlace { get; set; }
        public Nullable<int> TourGuideID { get; set; }
        public string Image1 { get; set; }
        public string Image2 { get; set; }
        public string Image3 { get; set; }
        public string TourDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Book> Books { get; set; }
        public virtual DepartureLocation DepartureLocation { get; set; }
        public virtual Destination Destination { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rating> Ratings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedule> Schedules { get; set; }
        public virtual TourGuide TourGuide { get; set; }
    }
}
